### ISSUE TITLE
请问窗口按钮能移动到左面吗？

### ISSUE THREAD

**Issue by yklove** [90du/imac-gtk-theme#3]

**Comment by 90du** [comment]
你使用的是什么桌面啊，gnome-shell可以在tweak-tool里面设置，deepin的话可以论坛搜索下，有解决方法

**Comment by yklove** [comment]
是deepin，已解决，感谢，但是发现chrome还有系统原声应用并没有生效，是否有更好的解决方案呢？ @90du

**Comment by 90du** [comment]
目前没有

**Comment by yklove** [comment]
好的，感谢告知
